name: LifeSteal
version: 0.0.4
main: io.github.superjoy0502.lifesteal.plugin.LifeStealPlugin
api-version: 1.18
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:1.6.0
  - org.jetbrains.kotlin:kotlin-reflect:1.6.0