name: LifeStealS
version: ${project.version}
author: Dongwoo Kim
main: io.github.superjoy0502.lifesteals.plugin.LifeStealPlugin
api-version: 1.18
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:1.6.0
  - org.jetbrains.kotlin:kotlin-reflect:1.6.0
  - io.github.monun:kommand:2.8.1
